(let_exp "let" @opener "in" @inner "end" @closer)
(cond_exp "if" @opener "then" @inner "else" @inner)
(iter_exp "while" @opener "do" @inner)
(case_exp "case" @opener "of" @inner)
(abstype_dec "abstype" @opener "with" @inner "end" @closer)
(local_dec "local" @opener "in" @inner "end" @closer)
(struct_strexp "struct" @opener "end" @closer)
(let_strexp "let" @opener "in" @inner "end" @closer)
(local_strdec "local" @opener "in" @inner "end" @closer)
(sig_sigexp "sig" @opener "end" @closer)
